# Generated by Django 4.2.24 on 2026-09-06 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('system', 'Padrão do Sistema')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=10)),
                ('notify_by_email', models.BooleanField(default=True, verbose_name='Receber Notificações por E-mail')),
                ('notify_by_push', models.BooleanField(default=True, verbose_name='Receber Push Notifications (Mobile)')),
                ('notify_by_whatsapp', models.BooleanField(default=False, verbose_name='Receber via WhatsApp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência do Usuário',
                'verbose_name_plural': 'Preferências dos Usuários',
            },
        ),
    ]
