# Generated by Django 4.2.11 on 2025-07-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="farm.farm",
                verbose_name="Fazenda",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offspring_father",
                to="animals.animal",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offspring_mother",
                to="animals.animal",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="animals.status"
            ),
        ),
    ]
