# Generated by Django 4.2.15 on 2025-09-18 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="dissociated_reasons",
            field=models.TextField(
                blank=True,
                choices=[("sold", "Sold"), ("dead", "Dead"), ("offline", "Offline")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="breed",
            name="isEnabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classification",
            name="isEnabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classification",
            name="isReproducible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="status",
            name="isEnabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="status",
            name="isReproducible",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animals.animal"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
