# Generated by Django 4.2.24 on 2025-11-03 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reproduction", "0004_semendonor_reproductioncycle_semen_donor"),
        ("animals", "0003_animal_dissociated_reasons_animal_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="semen_donor_father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offspring_donor_father",
                to="reproduction.semendonor",
                verbose_name="Pai (Doador de Sêmen)",
            ),
        ),
    ]
