# Generated by Django 4.2.24 on 2026-09-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_semen_donor_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='average_gestation_days',
            field=models.PositiveSmallIntegerField(default=283, verbose_name='Dias Médios de Gestação'),
        ),
    ]
