# Generated by Django 4.2.24 on 2026-09-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_seed_default_breeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('bezerra', 'Bezerra'), ('novilha', 'Novilha (Apta/Anestro)'), ('vaca_lactante', 'Vaca Lactante'), ('vaca_seca', 'Vaca Seca'), ('vaca_descarte', 'Vaca Descarte'), ('bezerro', 'Bezerro'), ('novilho', 'Novilho / Garrote'), ('reprodutor', 'Reprodutor / Touro'), ('rufiao', 'Rufião'), ('capao', 'Castrado / Boi Gordo')], default='bezerra', max_length=30, verbose_name='Categoria Zootécnica'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_castrated',
            field=models.BooleanField(default=False, verbose_name='É Castrado?'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_pregnant',
            field=models.BooleanField(default=False, verbose_name='Está Gestante?'),
        ),
    ]
