# Generated by Django 4.2.11 on 2025-07-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farm.address",
                verbose_name="Endereço da Fazenda",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="farms",
                through="farm.FarmUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuários Associados",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmuser",
            unique_together={("farm", "user")},
        ),
    ]
