# Generated by Django 4.2.11 on 2025-07-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="identifier",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Identificador da Fazenda",
            ),
        ),
    ]
