# Generated by Django 4.2.11 on 2025-08-31 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0003_alter_farm_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="identifier",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Identificador da Fazenda",
            ),
        ),
    ]
