# Generated by Django 4.2.24 on 2026-09-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='auto_update_categories',
            field=models.BooleanField(default=True, help_text='Se ativado, altera automaticamente a categoria do animal (ex: Bezerra -> Novilha -> Vaca) baseado na idade e eventos de parto.', verbose_name='Atualizar Categorias Zootécnicas Automaticamente'),
        ),
        migrations.AddField(
            model_name='farm',
            name='mating_age_months',
            field=models.PositiveIntegerField(default=24, verbose_name='Idade de Aptidão Reprodutiva / Adulto (Meses)'),
        ),
        migrations.AddField(
            model_name='farm',
            name='weaning_age_months',
            field=models.PositiveIntegerField(default=8, help_text='Idade em que bezerras(os) passam para a categoria de Novilha/Garrote.', verbose_name='Idade Média de Desmame (Meses)'),
        ),
    ]
