# Generated by Django 4.2.24 on 2026-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_farm_auto_update_categories_farm_mating_age_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='notify_calving_days_before',
            field=models.PositiveIntegerField(default=7, verbose_name='Dias de Antecedência para Alerta de Parto'),
        ),
        migrations.AddField(
            model_name='farm',
            name='notify_drug_withdrawal_days_before',
            field=models.PositiveIntegerField(default=2, verbose_name='Dias de Antecedência para Fim da Carência de Medicamentos'),
        ),
        migrations.AddField(
            model_name='farm',
            name='notify_heat_days_after_calving',
            field=models.PositiveIntegerField(default=45, verbose_name='Dias Pós-Parto para Alerta de Retorno ao Cio'),
        ),
    ]
