# Generated by Django 4.2.11 on 2025-07-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReproductionCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heat_start_date",
                    models.DateField(verbose_name="Data de Início do Cio"),
                ),
                ("mating_date", models.DateField(verbose_name="Data da Cobertura")),
                (
                    "mating_type",
                    models.CharField(
                        choices=[
                            ("natural", "Natural"),
                            ("artificial", "Artificial Insemination"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Cobertura",
                    ),
                ),
                (
                    "predicted_calving_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Prevista do Parto"
                    ),
                ),
                (
                    "actual_calving_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Real do Parto"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("calved", "Calved"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                            ("pending", "Pending Confirmation"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status do Ciclo",
                    ),
                ),
                (
                    "calf_born",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reproduction_cycle_of_origin",
                        to="animals.animal",
                        verbose_name="Bezerro Nascido",
                    ),
                ),
                (
                    "female_animal",
                    models.ForeignKey(
                        limit_choices_to={"sex": "female"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reproduction_cycles_as_female",
                        to="animals.animal",
                        verbose_name="Animal Fêmea",
                    ),
                ),
                (
                    "male_animal",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"sex": "male"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reproduction_cycles_as_male",
                        to="animals.animal",
                        verbose_name="Animal Macho (se natural)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo Reprodutivo",
                "verbose_name_plural": "Ciclos Reprodutivos",
                "ordering": ["-mating_date"],
            },
        ),
    ]
