# Generated by Django 4.2.24 on 2025-10-03 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_animal_dissociated_reasons_animal_is_active_and_more"),
        ("reproduction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reproductioncycle",
            name="female_animal",
            field=models.ForeignKey(
                limit_choices_to={"sex": "female"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reproduction_cycles_as_female",
                to="animals.animal",
                verbose_name="Animal Fêmea",
            ),
        ),
    ]
