# Generated by Django 4.2.24 on 2025-10-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reproduction", "0002_alter_reproductioncycle_female_animal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reproductioncycle",
            name="actual_calving_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data Real do Parto"
            ),
        ),
        migrations.AlterField(
            model_name="reproductioncycle",
            name="heat_start_date",
            field=models.DateTimeField(verbose_name="Data de Início do Cio"),
        ),
        migrations.AlterField(
            model_name="reproductioncycle",
            name="mating_date",
            field=models.DateTimeField(verbose_name="Data da Cobertura"),
        ),
        migrations.AlterField(
            model_name="reproductioncycle",
            name="predicted_calving_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data Prevista do Parto"
            ),
        ),
    ]
