# Generated by Django 4.2.24 on 2025-11-03 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_animal_dissociated_reasons_animal_is_active_and_more"),
        ("reproduction", "0003_alter_reproductioncycle_actual_calving_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemenDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do Doador"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Registro/Identificador",
                    ),
                ),
                (
                    "born_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Nascimento do Doador",
                    ),
                ),
                (
                    "origin_farm_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Fazenda de Origem/Central de Coleta",
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Coleta do Sêmen"
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="animals.breed",
                        verbose_name="Raça",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doador de Sêmen",
                "verbose_name_plural": "Doadores de Sêmen",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="reproductioncycle",
            name="semen_donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reproduction.semendonor",
                verbose_name="Doador de Sêmen (se IA)",
            ),
        ),
    ]
