# Generated by Django 4.2.24 on 2026-09-03 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_breed_average_gestation_days'),
        ('reproduction', '0004_semendonor_reproductioncycle_semen_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproductioncycle',
            name='male_animal',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproduction_cycles_as_father', to='animals.animal', verbose_name='Touro (se monta natural)'),
        ),
    ]
