# Generated by Django 4.2.24 on 2026-09-06 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0007_farm_notify_calving_days_before_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('reproduction', 'Reprodução e Partos'), ('clinical', 'Cuidados Clínicos e Medicamentos'), ('withdrawal', 'Período de Carência'), ('system', 'Avisos do Sistema')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta / Crítica')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255, verbose_name='Título do Alerta')),
                ('message', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('target_object_type', models.CharField(blank=True, help_text="Ex: 'animal', 'reproduction_cycle'", max_length=50, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida?')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='farm.farm', verbose_name='Fazenda Relacionada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Notificado')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
